# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FRPPractise' do
    use_frameworks!
    
    pod 'ReactiveCocoa', '~> 2.1.4'
    pod 'libextobjc', '~> 0.3'
    pod '500px-iOS-api', '~> 1.0.5'
    pod 'SVProgressHUD', '~> 0.9'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
    
    # Pods for FRPPractise
    
    target 'FRPPractiseTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
